package com.kas.mq.server.processors;

import com.kas.mq.impl.messages.IMqMessage;
import com.kas.mq.internal.EMqCode;
import com.kas.mq.internal.IMqConstants;
import com.kas.mq.internal.MqRemoteQueue;
import com.kas.mq.server.IRepository;
import com.kas.mq.server.internal.SessionHandler;

/**
 * Processor for handling repository updates (define/delete queues)
 * 
 * @author Pippo
 */
public class RepoUpdateProcessor extends AProcessor
{
  /**
   * Input
   */
  private String mManager;
  private String mQueue;
  private boolean mAdded;
  
  /**
   * Construct a {@link RepoUpdateProcessor}
   * 
   * @param request
   *   The request message
   * @param handler
   *   The session handler
   * @param repository
   *   The server's repository
   */
  public RepoUpdateProcessor(IMqMessage request, SessionHandler handler, IRepository repository)
  {
    super(request, handler, repository);
  }
  
  /**
   * Process request
   * 
   * @return
   *   response message generated by {@link #respond()}
   */
  public IMqMessage process()
  {
    mLogger.trace("RepoUpdateProcessor::process() - IN");
    
    if (!mConfig.isEnabled())
    {
      mDesc = "KAS/MQ server is disabled";
      mLogger.trace("RepoUpdateProcessor::process() - {}", mDesc);
    }
    else
    {
      mManager = mRequest.getStringProperty(IMqConstants.cKasPropertyRepoQmgrName, "");
      mQueue = mRequest.getStringProperty(IMqConstants.cKasPropertyRepoQueueName, "");
      mAdded = mRequest.getBoolProperty(IMqConstants.cKasPropertyRepoOperation, false);
      mLogger.trace("RepoUpdateProcessor::process() - Manager={}; Queue={}; Operation={}", mManager, mQueue, (mAdded ? "define" : "delete"));
      
      MqRemoteQueue mqrq;
      if (mAdded)
        mqrq = mRepository.defineRemoteQueue(mManager, mQueue);
      else
        mqrq = mRepository.deleteRemoteQueue(mManager, mQueue);
      
      if (mqrq != null)
      {
        mCode = EMqCode.cOkay;
        mDesc = "Queue " + mQueue + " was successfully " + (mAdded ? "defined in" : " deleted from ") + " remote KAS/MQ manager " + mManager;
      }
      else
      {
        mCode = EMqCode.cFail;
        mDesc = "Failed to " + (mAdded ? "define" : "delete") + " queue " + mQueue + " in Remote KAS/MQ manager " + mManager;
      }
      mLogger.trace("RepoUpdateProcessor::process() - {}", mDesc);
    }
    
    mLogger.trace("RepoUpdateProcessor::process() - OUT");
    return respond();
  }
}
