package com.kas.mq.server.processors.define;

import com.kas.infra.utils.StringUtils;
import com.kas.mq.impl.messages.IMqMessage;
import com.kas.mq.internal.EMqCode;
import com.kas.mq.internal.IMqConstants;
import com.kas.mq.server.IRepository;
import com.kas.mq.server.internal.SessionHandler;
import com.kas.mq.server.processors.AProcessor;
import com.kas.sec.access.AccessLevel;
import com.kas.sec.entities.GroupEntity;
import com.kas.sec.entities.GroupEntityDao;
import com.kas.sec.resources.EResourceClass;

/**
 * Processor for defining groups
 * 
 * @author Pippo
 */
public class DefineGroupProcessor extends AProcessor
{
  /**
   * Input
   */
  private String mGroup;
  private String mDescription;
  
  /**
   * Construct a {@link DefineGroupProcessor}
   * 
   * @param request
   *   The request message
   * @param handler
   *   The session handler
   * @param repository
   *   The server's repository
   */
  public DefineGroupProcessor(IMqMessage request, SessionHandler handler, IRepository repository)
  {
    super(request, handler, repository);
  }
  
  /**
   * Process request
   * 
   * @return
   *   response message generated by {@link #respond()}
   */
  public IMqMessage process()
  {
    mLogger.trace("DefineGroupProcessor::process() - IN");
    
    if (!mConfig.isEnabled())
    {
      mDesc = "KAS/MQ server is disabled";
      mLogger.trace("DefineGroupProcessor::process() - {}", mDesc);
    }
    else
    {
      mGroup = mRequest.getStringProperty(IMqConstants.cKasPropertyDefGroupName, null);
      mDescription = mRequest.getStringProperty(IMqConstants.cKasPropertyDefGroupDesc, "");
      mLogger.trace("DefineGroupProcessor::process() - Group={}", mGroup);
      
      if (!isAccessPermitted(EResourceClass.COMMAND, String.format("DEFINE_GROUP_%s", mGroup)))
      {
        mDesc = "User is not permitted to issue DEFINE_GROUP command";
        mLogger.warn(mDesc);
      }
      else if (!isAccessPermitted(EResourceClass.GROUP, mGroup, AccessLevel.WRITE_ACCESS))
      {
        mDesc = "User is not permitted to define groups";
        mLogger.warn(mDesc);
      }
      else
      {
        if (GroupEntityDao.getByName(mGroup) != null)
        {
          mDesc = "Group with name " + mGroup + " already exists";
          mLogger.warn(mDesc);
        }
        else
        {
          GroupEntity ge = GroupEntityDao.create(mGroup, mDescription);
          mLogger.trace("DefineGroupProcessor::process() - Created group {}", StringUtils.asPrintableString(ge));
          mDesc = "Group with name " + mGroup + " was successfully defined";
          mCode = EMqCode.cOkay;
        }
      }
    }
    
    mLogger.trace("DefineGroupProcessor::process() - OUT");
    return respond();
  }
}
