package com.kas.mq.server.processors.delete;

import java.util.Map;
import com.kas.comm.impl.NetworkAddress;
import com.kas.mq.impl.messages.IMqMessage;
import com.kas.mq.internal.EMqCode;
import com.kas.mq.internal.IMqConstants;
import com.kas.mq.internal.MqLocalQueue;
import com.kas.mq.server.IRepository;
import com.kas.mq.server.internal.MqServerConnection;
import com.kas.mq.server.internal.MqServerConnectionPool;
import com.kas.mq.server.internal.SessionHandler;
import com.kas.mq.server.processors.AProcessor;
import com.kas.sec.access.AccessLevel;
import com.kas.sec.resources.EResourceClass;

/**
 * Processor for deleting queues
 * 
 * @author Pippo
 */
public class DeleteQueueProcessor extends AProcessor
{
  /**
   * Input
   */
  private String mQueue;
  private boolean mForce;
  
  /**
   * Construct a {@link DeleteQueueProcessor}
   * 
   * @param request
   *   The request message
   * @param handler
   *   The session handler
   * @param repository
   *   The server's repository
   */
  DeleteQueueProcessor(IMqMessage request, SessionHandler handler, IRepository repository)
  {
    super(request, handler, repository);
  }
  
  /**
   * Process request
   * 
   * @return
   *   response message generated by {@link #respond()}
   */
  public IMqMessage process()
  {
    mLogger.trace("DeleteQueueProcessor::process() - IN");
    
    if (!mConfig.isEnabled())
    {
      mDesc = "KAS/MQ server is disabled";
      mLogger.trace("DeleteQueueProcessor::process() - {}", mDesc);
    }
    else
    {
      mQueue = mRequest.getStringProperty(IMqConstants.cKasPropertyDelQueueName, null);
      mForce = mRequest.getBoolProperty(IMqConstants.cKasPropertyDelForce, false);
      mLogger.trace("DeleteQueueProcessor::process() - Queue={}; Force={}", mQueue, mForce);
      
      MqLocalQueue mqlq = mRepository.getLocalQueue(mQueue);
      
      if (mqlq == null)
      {
        mDesc = "Queue with name \"" + mQueue + "\" doesn't exist";
        mLogger.trace("DeleteQueueProcessor::process() - {}", mDesc);
      }
      else if (!isAccessPermitted(EResourceClass.COMMAND, String.format("DELETE_QUEUE_%s", mQueue)))
      {
        mDesc = "User is not permitted to issue DELETE_QUEUE command";
        mLogger.warn(mDesc);
      }
      else if (!isAccessPermitted(EResourceClass.QUEUE, mQueue, AccessLevel.ALTER_ACCESS))
      {
        mDesc = "User is not permitted to delete queues";
        mLogger.warn(mDesc);
      }
      else if (mqlq.size() == 0)
      {
        mRepository.deleteLocalQueue(mQueue);
        mCode = EMqCode.cOkay;
        mDesc = "Queue with name \"" + mQueue + "\" was successfully deleted";
        mLogger.trace("DeleteQueueProcessor::process() - {}", mDesc);
      }
      else if (mForce)
      {
        int size = mqlq.size();
        mRepository.deleteLocalQueue(mQueue);
        mCode = EMqCode.cOkay;
        mDesc = "Queue with name \"" + mQueue + "\" was successfully deleted (" + size + " messages discarded)";
        mLogger.trace("DeleteQueueProcessor::process() - {}", mDesc);
      }
      else
      {
        int size = mqlq.size();
        mDesc = "Queue is not empty (" + size + " messages) and FORCE was not specified";
        mLogger.trace("DeleteQueueProcessor::process() - {}", mDesc);
      }
    }
    
    mLogger.trace("DeleteQueueProcessor::process() - OUT");
    return respond();
  }
  
  /**
   * Post-process queue deletion request.<br>
   * If queue deletion was successful, we need to inform remote KAS/MQ managers
   * that the local repository was updated and that they should update their repository
   * to reflect these changes.
   * 
   * @param reply
   *   The reply message the processor's {@link #process()} method generated
   * @return
   *   {@code true} in case the handler should continue process next request,
   *   {@code false} if it should terminate
   */
  public boolean postprocess(IMqMessage reply)
  {
    mLogger.trace("DeleteQueueProcessor::postprocess() - IN");
    
    if (mCode == EMqCode.cOkay)
    {
      Map<String, NetworkAddress> map = mConfig.getRemoteManagers();
      String localQmgr = mConfig.getManagerName();
      
      MqServerConnection conn = MqServerConnectionPool.getInstance().allocate();
      
      for (Map.Entry<String, NetworkAddress> entry : map.entrySet())
      {
        String remoteQmgrName  = entry.getKey();
        NetworkAddress address = entry.getValue();
        
        mLogger.trace("DeleteQueueProcessor::postprocess() - Notifying KAS/MQ server \"{}\" ({}) on repository update", remoteQmgrName, address);
        
        conn.connect(address.getHost(), address.getPort());
        if (conn.isConnected())
        {
          boolean logged = conn.login(IMqConstants.cSystemUserName, IMqConstants.cSystemPassWord);
          if (!logged)
          {
            mLogger.trace("DeleteQueueProcessor::postprocess() - Failed to login to remote KAS/MQ server at {}", address);
            continue;
          }
          
          boolean success = conn.notifyRepoUpdate(localQmgr, mQueue, false);
          mLogger.trace("DeleteQueueProcessor::postprocess() - Notification returned: {}", success);
          
          conn.disconnect();
        }
      }
      
      MqServerConnectionPool.getInstance().release(conn);
    }
    
    mLogger.trace("DeleteQueueProcessor::postprocess() - OUT");
    return true;
  }
}
